sudo: false
language: smalltalk

smalltalk: 
- Squeak-trunk
- Squeak-5.1

os:
- linux
- osx

before_install:
- sudo apt-get update 
- sudo apt-get install texlive-latex-extra
script:
- mkdir _build
- pdflatex -output-directory _build ./Programming_SRC/ccr_programming_src.tex

deploy:
  provider: releases
  api_key: a5d9f8e42f9983bd454322deda221c20c4eb1fbb
  file:
  - ./_build/Hello.pdf
  skip_cleanup: true
  on:
    tags: true
branch: master
